// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AccessToken struct {
	Token     string `json:"token"`
	TokenType string `json:"tokenType"`
	ExpiresAt int    `json:"expiresAt"`
}

type Mutation struct {
}

type Query struct {
}

type RefreshToken struct {
	Token     string `json:"token"`
	ExpiresAt int    `json:"expiresAt"`
}

type SignupRequest struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type SignupResponse struct {
	Succeeded    bool          `json:"succeeded"`
	AccessToken  *AccessToken  `json:"accessToken"`
	RefreshToken *RefreshToken `json:"refreshToken"`
	SignupToken  *SignupToken  `json:"signupToken"`
}

type SignupToken struct {
	Token     string `json:"token"`
	ExpiresAt int    `json:"expiresAt"`
}

type Student struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type StudentInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
