// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type AccessToken struct {
	Token     string `json:"token"`
	TokenType string `json:"tokenType"`
	ExpiresAt int    `json:"expiresAt"`
}

type EmailConfirmationRequest struct {
	AccountID string `json:"accountID"`
	Code      int    `json:"code"`
}

type GetStudentRequest struct {
	StudentID string `json:"studentID"`
}

type GetStudentsRequest struct {
	FilterType  string `json:"filterType"`
	FilterValue string `json:"filterValue"`
}

type Mutation struct {
}

type OperationStatus struct {
	Succeeded bool `json:"succeeded"`
}

type Query struct {
}

type RefreshToken struct {
	Token     string `json:"token"`
	ExpiresAt int    `json:"expiresAt"`
}

type SignupResponse struct {
	Succeeded    bool          `json:"succeeded"`
	AccessToken  *AccessToken  `json:"accessToken"`
	RefreshToken *RefreshToken `json:"refreshToken"`
	SignupToken  *SignupToken  `json:"signupToken"`
}

type SignupToken struct {
	Token     string `json:"token"`
	ExpiresAt int    `json:"expiresAt"`
}

type Student struct {
	StudentID          string  `json:"studentId"`
	Username           string  `json:"username"`
	Firstname          string  `json:"firstname"`
	Lastname           string  `json:"lastname"`
	Gender             string  `json:"gender"`
	DateOfBirth        string  `json:"dateOfBirth"`
	Status             bool    `json:"status"`
	Avatar             *string `json:"avatar,omitempty"`
	NotificationStatus bool    `json:"notificationStatus"`
	OnlineStatus       bool    `json:"onlineStatus"`
	DefaultAvatar      string  `json:"defaultAvatar"`
	CityID             string  `json:"cityId"`
}

type StudentInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type StudentSignupRequest struct {
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	Dob       string `json:"dob"`
	Gender    string `json:"gender"`
	GradID    string `json:"gradID"`
	CityID    int    `json:"cityID"`
}
